language: php

matrix:
    include:
        - php: 5.3
        - php: 5.4
        - php: 5.5
        - php: 5.6
        - php: 5.3
          env: deps=low
        - php: 5.6
          env: deps=high
        - php: nightly
        - php: hhvm-nightly
    allow_failures:
        - php: nightly
        - php: hhvm-nightly
    fast_finish: true

script:
  - phpunit --configuration phpunit.xml --coverage-clover=coverage.clover
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

matrix:
  fast_finish: true

notifications:
  email:
    - gjero@krsteski.de

